### ISSUE TITLE
"Under new management" read character by character by Apple VoiceOver

### ISSUE THREAD

**Issue by chriszs** [tophtucker/appletreeinn#17]
Sorry, I'm on an accessibility kick, and this jumped out (I was actually curious about the accessibility of a separate element on the page, which turned out to be less important): When I turn on Apple VoiceOver, it reads each character of the "UNDER NEW MANAGEMENT" wave-y banner separately, since they're marked up separately (due to the wave-y-ness). Might want to supply an alternative for screen readers.

**Comment by tophtucker** [comment]
Oh wow good point! I think I mostly fixed it. Now it reads "Under new management, empty group"; idk how to suppress the "empty group". Thanks for filing! Our first community issue!

**Comment by chriszs** [comment]
Awesome! Believe "empty group" is because all the children of the div with `role="presentation"` are marked as hidden, versus say, hiding the div itself. A different role might solve that.
