### ISSUE TITLE
OSTRICH ROOM NOW OPEN

### ISSUE THREAD

**Issue by ccollery** [tophtucker/appletreeinn#19]
A big banner on the main page that says 

OSTRICH ROOM NOW OPEN! WEDNESDAY THROUGH SATURDAY 4-10PM FOR DRINKS. FOOD STARTS AT 5PM. LIVE MUSIC EVERY WEDNESDAY AND SATURDAY.

**Comment by tophtucker** [comment]
closed by https://github.com/tophtucker/appletreeinn/commit/37c74d430872d91ad82f3708f316844bad454d56
