### ISSUE TITLE
Ostrich Room 4th of July week hours

### ISSUE THREAD

**Issue by ccollery** [tophtucker/appletreeinn#31]
update on website with holiday hours:

Wed Jul 3rd - earlier hours + no live music. 4-8pm drinks & food. no live music
Thu Jul 4th - earlier hours. 4-8pm drinks & food
Fri Jul 5th - business as usual.  4-10pm drinks & 5-10pm food
Sat Jul 6th - business as usual. 4-10pm drinks & 5-10pm food. live music. act TBD

**Comment by tophtucker** [comment]
done, fast and scrappy… also updated google maps with special holiday hours https://github.com/tophtucker/appletreeinn/commit/8ead79f013838c46afa7726be2ac97145f49a6ae

<img width="655" alt="image" src="https://github.com/tophtucker/appletreeinn/assets/841829/05bb8fe7-588d-475f-aed1-dd16d41803e6">
