### ISSUE TITLE
events this week

### ISSUE THREAD

**Issue by ccollery** [tophtucker/appletreeinn#60]
on ostrich room page, if you look at "events this week" on say, friday, it shows this fri & this sat but then next wed & next thu.  i think this could confuse ppl.

**Comment by tophtucker** [comment]
yup i agree, currently it just shows "the soonest upcoming wed" & "the soonest upcoming thurs" & so on, been meaning to fix by "batching by week", have an issue for it here, closing this one as a duplicate, THANKS FOR FILING CLAIRE!! 😘  https://github.com/tophtucker/appletreeinn/issues/54
