### ISSUE TITLE
add gift certificate link to baladi website 

### ISSUE THREAD

**Issue by ccollery** [tophtucker/appletreeinn#62]
heres the link (https://www.toasttab.com/apple-tree-inn-lenox-10-richmond-mountain-road/giftcards) - should prob go on website .

toph - would you mind adding it to the baladi page when you have time?

**Comment by tophtucker** [comment]
done in https://github.com/tophtucker/appletreeinn/commit/300eef599478484e13485183267cae50a63fac76
